# Generated by Django 4.2.16 on 2026-07-21 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('content_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('website_url', models.URLField(blank=True, default='', max_length=1000)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=1000)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('publish_date', models.DateField(blank=True, db_index=True, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.CharField(blank=True, default='Medvolt', max_length=255)),
                ('status', models.CharField(db_index=True, default='published', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_content',
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_data_systemlog',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('total_website_views', models.PositiveIntegerField(default=0)),
                ('total_website_sessions', models.PositiveIntegerField(default=0)),
                ('total_search_clicks', models.PositiveIntegerField(default=0)),
                ('total_search_impressions', models.PositiveIntegerField(default=0)),
                ('total_email_opens', models.PositiveIntegerField(default=0)),
                ('total_email_clicks', models.PositiveIntegerField(default=0)),
                ('average_email_open_rate', models.FloatField(default=0)),
                ('average_email_click_rate', models.FloatField(default=0)),
                ('recommendations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_weeklyreport',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('page_url', models.URLField(db_index=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('users', models.PositiveIntegerField(default=0)),
                ('engagement_time_seconds', models.FloatField(default=0)),
                ('traffic_source', models.CharField(default='all', max_length=255)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_metrics', to='analytics_engine.content')),
            ],
            options={
                'db_table': 'analytics_data_websiteanalytics',
                'ordering': ['-metric_date', '-views'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('page_url', models.URLField(db_index=True, max_length=1000)),
                ('query', models.CharField(blank=True, default='', max_length=1000)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('average_position', models.FloatField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_metrics', to='analytics_engine.content')),
            ],
            options={
                'db_table': 'analytics_data_searchconsoleanalytics',
                'ordering': ['-metric_date', '-clicks'],
            },
        ),
        migrations.CreateModel(
            name='MailerLiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('open_rate', models.FloatField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('click_rate', models.FloatField(default=0)),
                ('unsubscribes', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailerlite_metrics', to='analytics_engine.content')),
            ],
            options={
                'db_table': 'analytics_data_mailerliteanalytics',
                'ordering': ['-snapshot_date', '-sent_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='websiteanalytics',
            constraint=models.UniqueConstraint(fields=('metric_date', 'page_url', 'traffic_source'), name='unique_website_metric'),
        ),
        migrations.AddConstraint(
            model_name='searchconsoleanalytics',
            constraint=models.UniqueConstraint(fields=('metric_date', 'page_url', 'query'), name='unique_search_metric'),
        ),
        migrations.AddConstraint(
            model_name='mailerliteanalytics',
            constraint=models.UniqueConstraint(fields=('campaign_id', 'snapshot_date'), name='unique_mailerlite_snapshot'),
        ),
    ]
