# Generated by Django 4.2 on 2026-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('total_users', models.PositiveIntegerField(blank=True, null=True)),
                ('active_users', models.PositiveIntegerField(blank=True, null=True)),
                ('new_users', models.PositiveIntegerField(blank=True, null=True)),
                ('engaged_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(blank=True, null=True)),
                ('engagement_duration_seconds', models.FloatField(blank=True, null=True)),
                ('property_id', models.CharField(db_index=True, max_length=50)),
                ('metric_date', models.DateField(db_index=True)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_ga4dailymetric',
                'ordering': ['metric_date'],
            },
        ),
        migrations.CreateModel(
            name='GA4Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(db_index=True, max_length=50)),
                ('report_type', models.CharField(choices=[('summary', 'Site summary'), ('source_medium', 'Sessions by source / medium'), ('channel_group', 'Sessions by default channel group'), ('page', 'Page performance')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_key', models.CharField(db_index=True, default='custom', max_length=30)),
                ('property_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_ga4report',
                'ordering': ['-end_date', 'report_type'],
            },
        ),
        migrations.CreateModel(
            name='GA4ReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('total_users', models.PositiveIntegerField(blank=True, null=True)),
                ('active_users', models.PositiveIntegerField(blank=True, null=True)),
                ('new_users', models.PositiveIntegerField(blank=True, null=True)),
                ('engaged_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(blank=True, null=True)),
                ('engagement_duration_seconds', models.FloatField(blank=True, null=True)),
                ('dimension_value', models.CharField(blank=True, default='', max_length=2048)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga4_report_rows', to='analytics_engine.content')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='analytics_engine.ga4report')),
            ],
            options={
                'db_table': 'analytics_data_ga4reportrow',
                'ordering': ['report', '-sessions', '-views'],
            },
        ),
        migrations.AddConstraint(
            model_name='ga4report',
            constraint=models.UniqueConstraint(fields=('property_id', 'report_type', 'start_date', 'end_date'), name='unique_ga4_report_range'),
        ),
        migrations.AddConstraint(
            model_name='ga4dailymetric',
            constraint=models.UniqueConstraint(fields=('property_id', 'metric_date'), name='unique_ga4_daily_metric'),
        ),
        migrations.AddConstraint(
            model_name='ga4reportrow',
            constraint=models.UniqueConstraint(fields=('report', 'dimension_value'), name='unique_ga4_report_row'),
        ),
    ]
