# Generated by Django 4.2 on 2026-09-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_engine', '0002_ga4_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('search_type', models.CharField(default='web', max_length=20)),
                ('data_state', models.CharField(default='final', max_length=10)),
                ('metric_date', models.DateField(db_index=True)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_gscdailymetric',
                'ordering': ['metric_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('search_type', models.CharField(default='web', max_length=20)),
                ('data_state', models.CharField(default='final', max_length=10)),
                ('report_type', models.CharField(choices=[('summary', 'Property summary'), ('query', 'Query performance'), ('page', 'Page performance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_key', models.CharField(db_index=True, default='custom', max_length=30)),
                ('aggregation_type', models.CharField(blank=True, default='', max_length=20)),
                ('data_through', models.DateField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_gscreport',
                'ordering': ['-end_date', 'report_type'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
                ('dimension_value', models.CharField(blank=True, default='', max_length=2048)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='analytics_engine.searchconsolereport')),
            ],
            options={
                'db_table': 'analytics_data_gscreportrow',
                'ordering': ['report', '-clicks', '-impressions'],
            },
        ),
        migrations.AddConstraint(
            model_name='searchconsolereport',
            constraint=models.UniqueConstraint(fields=('site_url', 'search_type', 'data_state', 'report_type', 'start_date', 'end_date'), name='unique_gsc_report_range'),
        ),
        migrations.AddConstraint(
            model_name='searchconsoledailymetric',
            constraint=models.UniqueConstraint(fields=('site_url', 'search_type', 'data_state', 'metric_date'), name='unique_gsc_daily_metric'),
        ),
        migrations.AddConstraint(
            model_name='searchconsolereportrow',
            constraint=models.UniqueConstraint(fields=('report', 'dimension_value'), name='unique_gsc_report_row'),
        ),
    ]
