# Generated by Django 4.2 on 2026-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_engine', '0003_search_console_reports'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchconsoledailymetric',
            name='unique_gsc_daily_metric',
        ),
        migrations.RemoveConstraint(
            model_name='searchconsolereport',
            name='unique_gsc_report_range',
        ),
        migrations.AddField(
            model_name='searchconsolereport',
            name='preliminary_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchconsoledailymetric',
            name='data_state',
            field=models.CharField(choices=[('final', 'Finalized'), ('preliminary', 'Preliminary (not yet finalized)')], default='final', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='searchconsoledailymetric',
            constraint=models.UniqueConstraint(fields=('site_url', 'search_type', 'metric_date'), name='unique_gsc_daily_date'),
        ),
        migrations.AddConstraint(
            model_name='searchconsolereport',
            constraint=models.UniqueConstraint(fields=('site_url', 'search_type', 'report_type', 'start_date', 'end_date'), name='unique_gsc_report_dates'),
        ),
    ]
